// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjrtuawqbqzybexmkzmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqcnR1YXdxYnF6eWJleG1rem1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Mjg3NDIsImV4cCI6MjA2NjQwNDc0Mn0.Pd9q9G4vSABP1YW-YawNjPcuAaPYX1TqRV4ptDSytus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);